//! Roadmap **D14** — a full-mode artifact anchored to real published measurements, served
//! through the real service path.
//!
//! Companion to `cli_full_mode_e2e.rs` (perturbed-truth synthetic, known-answer recovery) and
//! `cli_boresight_real_data_e2e.rs` (real data, boresight mode). This file is the third
//! corner: **real data, full mode, and the first test in the repository that serves a
//! full-mode artifact through `compute_gain_from_request`.**
//!
//! # What is real here and what is not
//!
//! The measurement grid is generated by `cr159703_grid` (see that binary's module docs for
//! the fill, step by step, and for the list of fabrications it echoes on every run). It is
//! **this repository's own physics model plus a residual derived from digitized measurements
//! of NASA CR-159703's 1.22 m dish** — the hybrid fill the maintainer approved on 2026-07-29
//! after the data assessment concluded that no published dataset can drive full-mode fitting.
//! The dataset must never be quoted as measured.
//!
//! What the *real* data contributes, and what these tests therefore assert against:
//!
//! * the absolute gain anchor — the report's 41.4 dBi text gain for this configuration;
//! * 19 digitized sidelobe-envelope peaks across both principal planes and both sides of
//!   boresight, which set the residual's magnitude, its growth with cone angle, and the
//!   entire clock dependence of the fitted correction surface (the modelled feed is
//!   azimuthally symmetric, so every clock variation in the artifact came from measurements).
//!
//! # The defect this file found
//!
//! Nothing in the suite had ever served a full-mode artifact, and doing so immediately hit
//! roadmap unit **C13**: `calibrate` wrote the feed's design offset **vertex**-relative
//! (`(0, 0, f)`) while the service adds that field to an already-vertex-origin steering
//! position, so a full-mode artifact's feed landed at `z ≈ 2f`. On this geometry the phantom
//! defocus cost **27.3 dB** of boresight gain (41.09 → 13.83 dBi). Fixed under this unit;
//! `served_feed_sits_at_the_focus` below is the standing end-to-end guard, and the served
//! gain assertions would all fail loudly if it regressed.
//!
//! # The limitation this file measures
//!
//! The shipped correction surface places cone knots no closer than 2°, while this antenna's
//! lobes are 1.16° apart (λ/D at 12.1 GHz). The digitized peaks scatter by several dB about
//! any curve that coarse — genuine lobe-to-lobe structure the surface cannot carry — so the
//! fill deliberately injects only the trend, and the per-peak agreement below is budgeted for
//! the difference. That budget is a *measurement of a known limitation*, not an accuracy
//! claim: see `docs/findings-2026-08-02-correction-surface-angular-resolution.md`.

use antenna_model::api::schemas::{GainRequest, GainResponse, Position3D};
use antenna_model::data::repository::CalibrationRepository;
use antenna_model::data::types::{AntennaCalibration, CalibrationStatus};
use antenna_model::model::coordinates_3d::geodetic_to_ecef;
use antenna_model::model::evaluate_correction;
use antenna_model::service::compute_gain_from_request;
use serde_json::Value;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::OnceLock;

// ============================================================================
// Identity of the run
// ============================================================================

const ANTENNA_ID: &str = "nasa_cr159703_122m";
const FEED_ID: &str = "kumar_12ghz";
const ANTENNA_CLASS: &str = "NASA_CR159703_1p22m";

/// Frequency both digitized cuts were recorded at, and the only frequency at which this file
/// compares against measurements.
///
/// Restated from the generator rather than imported — a test binary cannot see another
/// binary's constants — and therefore **pinned** against the summary JSON by
/// `shared_constants_match_the_generator`. Every restated value in this block is.
const ANCHOR_FREQUENCY_MHZ: f64 = 12100.0;

/// The report's published gain for the modelled configuration, dBi (NASA CR-159703 p. 58).
const PUBLISHED_GAIN_DBI: f64 = 41.4;

/// Uncertainty carried by that absolute anchor, dB — see the generator's constant of the
/// same name. Common mode across every level in the dataset.
const ABSOLUTE_ANCHOR_UNCERTAINTY_DB: f64 = 0.5;

/// Half-width of the peak-envelope comparison window, degrees. Must match the generator's
/// `ENVELOPE_HALF_WIDTH_DEG`: the residual was *defined* through this window, so comparing
/// the served pattern through a different one would compare two different quantities — and
/// silently, because the 8.5 dB structure allowance is wide enough to swallow the difference.
const ENVELOPE_HALF_WIDTH_DEG: f64 = 0.6;

/// Step at which the served pattern is sampled inside that window, degrees.
const ENVELOPE_SAMPLE_STEP_DEG: f64 = 0.05;

// ============================================================================
// Tolerances — every one measured on 2026-08-02, none wished for
// ============================================================================

/// Ceiling on the fit's own RMSE against the synthesized grid, dB.
///
/// Measured **0.0272 dB** over 3240 points against 960 coefficients. This is the fit
/// reproducing the *fill*, so it says nothing about agreement with measurements; what it does
/// say is that the correction surface can represent what the fill asks of it — an 11 dB
/// residual that grows with cone angle and varies with clock — to under 0.03 dB. The +0.01 dB
/// headroom is for cross-platform libm differences, sized the same way as
/// `cli_full_mode_e2e.rs`'s ceiling.
const CORRECTED_RMSE_CEILING_DB: f64 = 0.0272 + 0.01;

/// How closely calibrate's reported model-only RMSE must reproduce the residual RMS the
/// generator says it injected, dB.
///
/// Measured **identical to four decimals** (11.0266 dB both sides) — as it must be: the
/// generator writes `model + residual` and calibrate differences the same model back out, so
/// any gap is the two sides having built *different models* from the same antenna class.
/// That is the D17 failure mode one seam further out, and this is its guard: 1e-3 dB is far
/// below anything a real divergence would produce and far above f64 formatting noise (the CSV
/// carries 6 decimals).
const MODEL_AGREEMENT_DB: f64 = 1e-3;

/// How closely the served correction must reproduce the residual the fill injected, dB.
///
/// Measured worst **0.2423 dB** across the 19 anchor locations, and it is worth knowing where
/// that concentrates: the four largest errors (0.24, 0.18, 0.06, 0.05 dB) are all at a
/// half-plane's *outermost* anchor, where the injected residual has a slope discontinuity —
/// the fill holds the trend constant beyond the last digitized peak rather than extrapolating
/// a polynomial. A C⁰ kink between knots is the one shape an order-4 spline cannot follow, so
/// this is the fill's own conservatism showing up, not a fitting defect. Every anchor away
/// from a kink lands inside 0.05 dB.
///
/// This is the tight, purely internal assertion of the file: fill → CSV → fit → artifact →
/// service loader → 4D interpolator, with no measurement uncertainty in it at all. A
/// regression anywhere in that chain shows up here first and unambiguously.
const CORRECTION_FIDELITY_DB: f64 = 0.30;

/// Budget on the served boresight gain against the report's published figure, dB.
///
/// Measured **−0.0935 dB** (served 41.3065 dBi). The number is not free: the fill's boresight
/// residual is fitted, not imposed — the trend is a weighted least-squares quadratic through
/// the boresight anchor *and* the sidelobe peaks, so it need not pass exactly through
/// 41.4 dBi. What this asserts is that after the whole pipeline the served gain still lands
/// well inside the anchor's own 0.5 dB uncertainty. It is also the assertion with the most
/// power against C13: a vertex-relative feed offset lands here 27 dB low.
const BORESIGHT_BUDGET_DB: f64 = 0.25;

/// Budget on each digitized peak, dB — **itemised, and one item is a known limitation.**
///
/// * the peak's own digitization uncertainty (`uncertainty_db`, 0.5–1.5 dB per row), plus
/// * [`ABSOLUTE_ANCHOR_UNCERTAINTY_DB`] (0.5 dB), the common-mode gain anchor, plus
/// * this term: the lobe-scale structure the pipeline cannot represent.
///
/// The fourth stated uncertainty — the ±0.3–0.5° **angle** uncertainty on each digitized peak
/// — is not a dB term here, because it is spent structurally instead: both sides are read
/// through the same ±0.6° peak-envelope window ([`ENVELOPE_HALF_WIDTH_DEG`]), which is wider
/// than the angle uncertainty and is exactly the treatment an envelope digitization calls for.
/// Converting it to dB and adding it would double-count.
///
/// The third term is not slack for fit error. The digitized peaks deviate from the smoothest
/// curve the shipped knot spacing can carry by up to **8.42 dB** (measured; the deviation
/// column of the generator's anchor table), because a 2° minimum cone knot spacing cannot
/// follow a pattern whose lobes are 1.16° apart. The largest served error is **8.03 dB**, at
/// the −3.6° H-plane row — consistent with that deviation, and at the same place. The
/// limitation is *reported*, not absorbed silently — D14 filed it
/// (`docs/findings-2026-08-02-correction-surface-angular-resolution.md`) and **D21 made the
/// artifact state it**: see
/// [`the_artifact_records_that_its_knots_cannot_resolve_this_antennas_lobe_structure`], which
/// pins the same limitation as a *measured ratio* (0.577 cone / 0.119 clock knots per lobe
/// period) rather than as slack in this budget. That is why this file also asserts
/// [`ANCHOR_RMS_BUDGET_DB`], [`MIN_ANCHORS_IMPROVED`] and the RMS improvement over the
/// uncorrected model: those are what would actually notice a pipeline regression, which this
/// bound alone is too loose to catch.
///
/// **If the knot configuration changes, this constant and the two ratios move together** —
/// they are three views of one quantity. Re-measure all three; do not widen this one alone.
const ANCHOR_STRUCTURE_ALLOWANCE_DB: f64 = 8.5;

/// RMS budget over all 19 anchors, dB. Measured **3.19 dB**, dominated by the two peaks the
/// digitization itself annotates as spikes rather than lobes (−3.6° and −3.2°, which
/// contribute 8.03 and 6.55 dB of it); the other 17 sit at 0.29–4.95 dB. Unlike the per-anchor
/// bound this one moves if the pipeline degrades anywhere, so it is the standing guard.
const ANCHOR_RMS_BUDGET_DB: f64 = 3.5;

/// The corrected pattern must beat the uncorrected model at the anchors by at least this
/// factor in RMS. Measured **3.6×** (11.58 dB → 3.19 dB).
const MIN_RMS_IMPROVEMENT_FACTOR: f64 = 3.0;

/// How many of the 19 digitized peaks the correction must bring *closer* than the uncorrected
/// model leaves them.
///
/// Measured **17 of 19**, and the two exceptions are the same two rows the digitization itself
/// annotates as spikes rather than lobes: −3.6° H ("minor spike near first null", chart level
/// −41 dB) and −3.2° E ("narrow spike", −39.5 dB). Both sit within ~1.5 dB of the *uncorrected*
/// model's own first sidelobe, so there is nothing there for a correction to improve — and the
/// fitted trend, which follows the genuine sidelobes either side of them at +7 to +13 dB,
/// necessarily overshoots them. Asserting "closer at every anchor" would be asserting that a
/// 2°-resolution surface can follow a 1.16° lobe period, which is exactly the limitation this
/// unit reports rather than papers over.
const MIN_ANCHORS_IMPROVED: usize = 17;

// ============================================================================
// Running the pipeline: generator → calibrate → service loader
// ============================================================================

struct Pipeline {
    /// The generated measurement grid, kept so the script's `--validate` argument set can be
    /// exercised against the same data without regenerating it.
    csv: PathBuf,
    artifact: PathBuf,
    summary: Value,
    report: Value,
    generator_output: String,
    calibrate_output: String,
    _dir: tempfile::TempDir,
}

impl Pipeline {
    /// Load through the **service's** loader, not calibrate's own round-trip code.
    fn load(&self) -> AntennaCalibration {
        antenna_model::data::loader::load_calibration_artifact(&self.artifact).unwrap_or_else(|e| {
            panic!(
                "the service loader must accept the full-mode artifact calibrate just wrote: \
                 {e}\n{}",
                self.calibrate_output
            )
        })
    }

    fn anchors(&self) -> Vec<Anchor> {
        self.summary["anchors"]
            .as_array()
            .expect("summary carries an anchor table")
            .iter()
            .map(|a| Anchor {
                cut_id: a["cut_id"].as_str().expect("cut_id").to_string(),
                clock_deg: number(a, "clock_deg"),
                cone_deg: number(a, "cone_deg"),
                level_db_rel_peak: number(a, "level_db_rel_peak"),
                uncertainty_db: number(a, "uncertainty_db"),
                measured_dbi: number(a, "measured_dbi"),
                model_envelope_dbi: number(a, "model_envelope_dbi"),
                trend_db: number(a, "trend_db"),
            })
            .collect()
    }
}

/// One digitized peak, as the generator recorded it in the summary.
#[derive(Debug, Clone)]
struct Anchor {
    cut_id: String,
    clock_deg: f64,
    cone_deg: f64,
    level_db_rel_peak: f64,
    uncertainty_db: f64,
    measured_dbi: f64,
    model_envelope_dbi: f64,
    trend_db: f64,
}

fn number(value: &Value, key: &str) -> f64 {
    value[key]
        .as_f64()
        .unwrap_or_else(|| panic!("summary field {key} is not a number: {value}"))
}

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

/// The digitized peaks, as committed. Single source of truth: the generator reads this same
/// file, and `summary_anchors_match_the_digitized_peaks` re-derives the anchors from it.
fn peaks_file() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("antenna-model")
        .join("tests")
        .join("fixtures")
        .join("reference_datasets")
        .join("sidelobe_data")
        .join("nasa_cr159703_pattern_peaks.psv")
}

/// Generate the grid and calibrate it — **once** per test binary.
///
/// Both binaries are the real ones (`CARGO_BIN_EXE_*`), so this exercises argument parsing, the
/// CSV round trip and the artifact writer the way `scripts/generate-cr159703-artifact.sh` does.
/// It is **not** the script's exact argument set: this run omits `--validate` (and `--metadata`),
/// because cross-validation costs five extra refits of a 960-coefficient system and nothing
/// below reads it. The script's flags are covered separately, by
/// `the_scripts_validated_run_produces_an_artifact` — without that, "the script is pinned by the
/// tests" would be a claim about a code path no test runs.
fn pipeline() -> &'static Pipeline {
    static PIPELINE: OnceLock<Pipeline> = OnceLock::new();
    PIPELINE.get_or_init(|| {
        let dir = tempfile::tempdir().expect("temp dir");
        let csv = dir.path().join("cr159703_grid.csv");
        let summary_path = dir.path().join("cr159703_grid_summary.json");
        let artifact = dir.path().join("cr159703_122m.bin");
        let report_path = dir.path().join("report.json");
        let classes_file = fixture("nasa_cr159703_122m_classes.yaml");

        let generator = Command::new(env!("CARGO_BIN_EXE_cr159703_grid"))
            .arg("--peaks")
            .arg(peaks_file())
            .arg("--classes-file")
            .arg(&classes_file)
            .args(["--antenna-class", ANTENNA_CLASS])
            .arg("--output")
            .arg(&csv)
            .arg("--summary")
            .arg(&summary_path)
            .output()
            .expect("run the cr159703_grid binary");
        let generator_output = format!(
            "--- cr159703_grid stdout ---\n{}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&generator.stdout),
            String::from_utf8_lossy(&generator.stderr)
        );
        assert!(
            generator.status.success(),
            "the grid generator failed with {:?}\n{generator_output}",
            generator.status.code()
        );

        let calibrate = Command::new(env!("CARGO_BIN_EXE_calibrate"))
            .args(["--calibration-mode", "full"])
            .arg("--input")
            .arg(&csv)
            .arg("--output")
            .arg(&artifact)
            .args(["--antenna-id", ANTENNA_ID])
            .args(["--feed-id", FEED_ID])
            .args(["--antenna-class", ANTENNA_CLASS])
            .arg("--classes-file")
            .arg(&classes_file)
            .args([
                "--antenna-name",
                "NASA CR-159703 1.22 m (real-anchored hybrid fill)",
            ])
            .arg("--report")
            .arg(&report_path)
            .output()
            .expect("run the calibrate binary");
        let calibrate_output = format!(
            "--- calibrate stdout ---\n{}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&calibrate.stdout),
            String::from_utf8_lossy(&calibrate.stderr)
        );
        assert!(
            calibrate.status.success(),
            "calibrate failed with {:?}\n{calibrate_output}",
            calibrate.status.code()
        );

        let summary = serde_json::from_str(
            &std::fs::read_to_string(&summary_path).expect("read the generator summary"),
        )
        .expect("parse the generator summary as JSON");
        let report = serde_json::from_str(
            &std::fs::read_to_string(&report_path).expect("read the validation report"),
        )
        .expect("parse the validation report as JSON");

        Pipeline {
            csv,
            artifact,
            summary,
            report,
            generator_output,
            calibrate_output,
            _dir: dir,
        }
    })
}

fn repository() -> &'static CalibrationRepository {
    static REPO: OnceLock<CalibrationRepository> = OnceLock::new();
    REPO.get_or_init(|| {
        let mut repo = CalibrationRepository::new();
        repo.add_calibration(pipeline().load());
        repo
    })
}

// ============================================================================
// Serving a chosen (cone, clock) direction
// ============================================================================

/// Build a request whose emitter sits at polar angle `cone_deg` and clock angle `clock_deg`
/// in the antenna frame.
///
/// The antenna frame is defined by the vehicle→boresight vector plus an azimuth-zero
/// reference, and with no attitude quaternion that reference is the Earth-Z cross product
/// (`coordinates_3d::antenna_frame_axes`). That construction is **replicated here**, which is
/// the only way to aim a request at a specific clock angle from the outside — and
/// `request_geometry_lands_on_the_requested_angles` asserts the replication still agrees with
/// the service, so a convention change surfaces as one obvious failure instead of nineteen
/// mysterious ones.
///
/// `feed_pointing_location` is the boresight target, so the derived feed displacement is zero
/// and the served antenna is the focused one the calibration describes. Aiming the feed
/// anywhere else serves a coma-steered antenna and every comparison here becomes meaningless.
fn request_for(cone_deg: f64, clock_deg: f64, frequency_mhz: f64) -> GainRequest {
    const VEHICLE: (f64, f64, f64) = (-118.0, 34.0, 100.0);
    const TARGET: (f64, f64, f64) = (-117.0, 35.0, 400_000.0);

    let vehicle = geodetic_to_ecef(VEHICLE.0, VEHICLE.1, VEHICLE.2).expect("vehicle ECEF");
    let target = geodetic_to_ecef(TARGET.0, TARGET.1, TARGET.2).expect("target ECEF");

    let boresight = (
        target.0 - vehicle.0,
        target.1 - vehicle.1,
        target.2 - vehicle.2,
    );
    let range = (boresight.0.powi(2) + boresight.1.powi(2) + boresight.2.powi(2)).sqrt();
    let z = (
        boresight.0 / range,
        boresight.1 / range,
        boresight.2 / range,
    );

    // Azimuth-zero reference: Earth-Z × boresight, normalized (the |z_z| < 0.99 branch of
    // `antenna_frame_axes`; this geometry looks far from the pole, so that branch is the one
    // taken — asserted below).
    assert!(
        z.2.abs() < 0.99,
        "the test geometry must stay in the Earth-Z branch of the azimuth reference"
    );
    let x_raw = (-z.1, z.0, 0.0_f64);
    let x_mag = (x_raw.0.powi(2) + x_raw.1.powi(2) + x_raw.2.powi(2)).sqrt();
    let x = (x_raw.0 / x_mag, x_raw.1 / x_mag, x_raw.2 / x_mag);
    // Y completes the right-handed system: Y = Z × X.
    let y = (
        z.1 * x.2 - z.2 * x.1,
        z.2 * x.0 - z.0 * x.2,
        z.0 * x.1 - z.1 * x.0,
    );

    let (theta, phi) = (cone_deg.to_radians(), clock_deg.to_radians());
    let (st, ct) = (theta.sin(), theta.cos());
    let (sp, cp) = (phi.sin(), phi.cos());
    let direction = (
        x.0 * st * cp + y.0 * st * sp + z.0 * ct,
        x.1 * st * cp + y.1 * st * sp + z.1 * ct,
        x.2 * st * cp + y.2 * st * sp + z.2 * ct,
    );

    let emitter = Position3D::ecef(
        vehicle.0 + direction.0 * range,
        vehicle.1 + direction.1 * range,
        vehicle.2 + direction.2 * range,
    );
    let boresight_target = Position3D::ecef(target.0, target.1, target.2);

    GainRequest {
        antenna_id: ANTENNA_ID.to_string(),
        feed_id: FEED_ID.to_string(),
        vehicle_position: Position3D::ecef(vehicle.0, vehicle.1, vehicle.2),
        reflector_boresight: boresight_target.clone(),
        feed_pointing_location: boresight_target,
        emitter_position: emitter,
        frequency_mhz,
        pointing_frequency_mhz: None,
        include_reference: false,
        vehicle_attitude: None,
    }
}

fn serve(cone_deg: f64, clock_deg: f64, frequency_mhz: f64) -> GainResponse {
    compute_gain_from_request(
        &request_for(cone_deg, clock_deg, frequency_mhz),
        repository(),
    )
    .unwrap_or_else(|e| {
        panic!("serving cone {cone_deg}° clock {clock_deg}° at {frequency_mhz} MHz failed: {e}")
    })
}

/// The served pattern's peak envelope near `cone_deg`, read exactly as the fill read the
/// model's: `max` over `± ENVELOPE_HALF_WIDTH_DEG`.
fn served_envelope_dbi(cone_deg: f64, clock_deg: f64, frequency_mhz: f64) -> f64 {
    let lo = (cone_deg - ENVELOPE_HALF_WIDTH_DEG).max(0.0);
    let hi = cone_deg + ENVELOPE_HALF_WIDTH_DEG;
    let steps = ((hi - lo) / ENVELOPE_SAMPLE_STEP_DEG).round() as usize;

    (0..=steps)
        .map(|i| {
            let theta = lo + (i as f64) * ENVELOPE_SAMPLE_STEP_DEG;
            serve(theta, clock_deg, frequency_mhz).gain_db
        })
        .fold(f64::NEG_INFINITY, f64::max)
}

fn correction_applied(response: &GainResponse) -> bool {
    response
        .calibration_status
        .as_ref()
        .map(|s| s.correction_applied)
        .unwrap_or(false)
}

// ============================================================================
// The fill says what the report says
// ============================================================================

/// Every anchor the generator used must be a row of the committed PSV, read independently
/// here. The generator could otherwise pick up a different cut, a different frequency or a
/// different dish and still produce a beautifully smooth fill.
#[test]
fn summary_anchors_match_the_digitized_peaks() {
    let path = peaks_file();
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));

    let mut lines = text
        .lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty());
    let header: Vec<&str> = lines
        .next()
        .expect("PSV header")
        .split('|')
        .map(str::trim)
        .collect();
    let column = |fields: &[&str], name: &str| -> String {
        let idx = header
            .iter()
            .position(|h| *h == name)
            .unwrap_or_else(|| panic!("no '{name}' column in {}", path.display()));
        fields[idx].to_string()
    };

    // (cut_id, |angle|, positive side, level, uncertainty) for the two cuts the fill uses.
    let published: Vec<(String, f64, bool, f64, f64)> = lines
        .map(|line| {
            let fields: Vec<&str> = line.split('|').map(str::trim).collect();
            let angle: f64 = column(&fields, "peak_angle_deg").parse().expect("angle");
            (
                column(&fields, "cut_id"),
                angle.abs(),
                angle > 0.0,
                column(&fields, "level_db_rel_peak").parse().expect("level"),
                column(&fields, "uncertainty_db")
                    .parse()
                    .expect("uncertainty"),
            )
        })
        .collect();

    let anchors = pipeline().anchors();
    assert!(
        !anchors.is_empty(),
        "the generator summary carried no anchors\n{}",
        pipeline().generator_output
    );

    for anchor in &anchors {
        // Clock 0/90 are the positive side of the chart, 180/270 the negative — the
        // generator's documented convention.
        let positive_side = anchor.clock_deg < 180.0;
        let hit = published.iter().any(|(cut, cone, positive, level, unc)| {
            *cut == anchor.cut_id
                && (*cone - anchor.cone_deg).abs() < 1e-9
                && *positive == positive_side
                && (*level - anchor.level_db_rel_peak).abs() < 1e-9
                && (*unc - anchor.uncertainty_db).abs() < 1e-9
        });
        assert!(
            hit,
            "anchor {anchor:?} is not a row of {} — the fill is anchored to something other \
             than the committed digitization",
            path.display()
        );

        // And the absolute level is the chart level referred to the report's text gain.
        let expected = PUBLISHED_GAIN_DBI + anchor.level_db_rel_peak;
        assert!(
            (anchor.measured_dbi - expected).abs() < 1e-9,
            "anchor at cone {}° carries {} dBi, but its chart level {} dB against the \
             published {PUBLISHED_GAIN_DBI} dBi is {expected} dBi",
            anchor.cone_deg,
            anchor.measured_dbi,
            anchor.level_db_rel_peak
        );
    }

    // Both principal planes and both sides of boresight, or the clock axis of the fitted
    // surface rests on an assumption rather than on data.
    let clocks: std::collections::BTreeSet<i64> =
        anchors.iter().map(|a| a.clock_deg as i64).collect();
    assert_eq!(
        clocks,
        [0, 90, 180, 270].into_iter().collect(),
        "the fill must be anchored on all four measured half-planes"
    );
}

// ============================================================================
// The artifact
// ============================================================================

/// Every value this file restates from the generator must still be the generator's.
///
/// Three of them are load-bearing in a way that fails *silently* rather than loudly:
/// the envelope half-width defines the quantity both sides compare (a mismatch compares two
/// different things, and the 8.5 dB structure allowance is wide enough to hide it), the anchor
/// frequency decides which slice of a frequency-varying model is compared, and the absolute
/// anchor is what "measured dBi" means. The generator writes all three into the summary JSON
/// this file already parses, so the pin costs nothing.
#[test]
fn shared_constants_match_the_generator() {
    let summary = &pipeline().summary;

    let checks = [
        (
            "envelope_half_width_deg",
            number(&summary["model"], "envelope_half_width_deg"),
            ENVELOPE_HALF_WIDTH_DEG,
        ),
        (
            "anchor_frequency_mhz",
            number(&summary["source"], "anchor_frequency_mhz"),
            ANCHOR_FREQUENCY_MHZ,
        ),
        (
            "absolute_anchor_dbi",
            number(&summary["source"], "absolute_anchor_dbi"),
            PUBLISHED_GAIN_DBI,
        ),
        (
            "absolute_anchor_uncertainty_db",
            number(&summary["source"], "absolute_anchor_uncertainty_db"),
            ABSOLUTE_ANCHOR_UNCERTAINTY_DB,
        ),
    ];

    for (name, generator_value, test_value) in checks {
        assert_eq!(
            generator_value, test_value,
            "{name}: the generator used {generator_value} and this file assumes {test_value}; \
             they must move together or every comparison below is between two different \
             quantities"
        );
    }
}

#[test]
fn full_mode_artifact_loads_and_presents_as_calibrated() {
    let run = pipeline();
    let calibration = run.load();

    assert_eq!(calibration.antenna_id, ANTENNA_ID);
    assert_eq!(calibration.feed_id, FEED_ID);
    assert!(
        matches!(
            calibration.calibration_status,
            Some(CalibrationStatus::FullyCalibrated { .. })
        ),
        "a full-mode artifact must serve as Calibrated; got {:?}",
        calibration.calibration_status
    );
    assert!(
        calibration.correction_surface.is_some(),
        "full mode must ship a correction surface"
    );
    assert!(
        !calibration.physics_is_uncorrected(),
        "a corrected artifact must present as corrected physics, so the service evaluates it \
         with spillover and the F7 floor off — the gates the fill's residual was defined under"
    );

    // Coverage spans the generated grid, so every anchor below is interpolated rather than
    // extrapolated.
    let coverage = calibration
        .calibration_coverage
        .as_ref()
        .expect("a full-mode artifact records its coverage");
    assert_eq!(coverage.frequency_range, (11700.0, 12200.0));
    assert_eq!(coverage.elevation_range, (0.0, 14.0));
    assert_eq!(coverage.azimuth_range, (0.0, 350.0));
    assert!(coverage.has_correction_surface);

    // The surface the shipped knot configuration declares: 4/6/8 internal knots at order 4
    // over axes with enough distinct values to place every one of them strictly inside
    // (roadmap D19/D20), i.e. 12 × 10 × 8 × 5 with azimuth fastest.
    let surface = calibration
        .correction_surface
        .as_ref()
        .expect("correction surface");
    assert_eq!(
        surface.shape,
        [12, 10, 8, 5],
        "the grid is sized so the fitter can place all 4/6/8 requested knots; a different \
         shape means an axis lost knots to interior-only placement or minimum spacing"
    );
}

/// The D9 exemplar script's own argument set: `--validate` (5-fold) and `--metadata`.
///
/// Everything else in this file runs `calibrate` without them, so without this test the
/// script's documented flow would be pinned by nothing — and one of those flags can now *abort
/// artifact production*: since roadmap D20 an underdetermined fit is a hard error, and a CV fold
/// trains on `(1 − 1/folds)` of the grid, so a dataset that clears the coefficient count on the
/// whole set but not on a fold produces **no artifact with `--validate` and a good one
/// without**. This grid is sized to clear it either way (3240 points, 2592 per training split,
/// 960 coefficients) — that is the property being pinned.
///
/// The cross-validation numbers used to be a known defect pinned as one — folds were
/// contiguous slices of a grid-ordered file, so the edge folds held out a whole frequency slab
/// and scored an extrapolation. **Roadmap D22 landed 2026-08-03 and the pin is inverted**, as
/// its own comment instructed: strided folds put this artifact's five fold RMSEs at
/// 0.0286 / 0.0312 / 0.0305 / 0.0602 / 0.0458 dB, where they were
/// 10.0688 / 0.5600 / 0.1223 / 0.6436 / 10.8570. The worst fold went from **370× the in-sample
/// RMSE to 2.2×**, which is what a cross-validation figure is supposed to look like on a
/// surface that interpolates well.
#[test]
fn the_scripts_validated_run_produces_an_artifact() {
    let run = pipeline();
    let dir = tempfile::tempdir().expect("temp dir");
    let artifact = dir.path().join("validated.bin");
    let report_path = dir.path().join("validated_report.json");
    let metadata_path = dir.path().join("validated_metadata.json");

    let output = Command::new(env!("CARGO_BIN_EXE_calibrate"))
        .args(["--calibration-mode", "full"])
        .arg("--input")
        .arg(&run.csv)
        .arg("--output")
        .arg(&artifact)
        .args(["--antenna-id", ANTENNA_ID])
        .args(["--feed-id", FEED_ID])
        .args(["--antenna-class", ANTENNA_CLASS])
        .arg("--classes-file")
        .arg(fixture("nasa_cr159703_122m_classes.yaml"))
        .arg("--validate")
        .arg("--report")
        .arg(&report_path)
        .arg("--metadata")
        .arg(&metadata_path)
        .output()
        .expect("run the calibrate binary with the script's flags");
    let text = format!(
        "--- stdout ---\n{}\n--- stderr ---\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.status.success(),
        "the script's own argument set failed with {:?}\n{text}",
        output.status.code()
    );

    antenna_model::data::loader::load_calibration_artifact(&artifact)
        .unwrap_or_else(|e| panic!("the validated run must still write a loadable artifact: {e}"));
    assert!(
        metadata_path.exists(),
        "--metadata must write the sidecar the script asks for"
    );

    let report: Value = serde_json::from_str(
        &std::fs::read_to_string(&report_path).expect("read the validated report"),
    )
    .expect("parse the validated report");

    let folds = report["cross_validation"]["fold_rmse_values"]
        .as_array()
        .unwrap_or_else(|| panic!("--validate must produce cross-validation; report:\n{report:#}"));
    assert_eq!(folds.len(), 5, "clap's --cv-folds default is 5");

    let values: Vec<f64> = folds
        .iter()
        .map(|v| v.as_f64().expect("fold RMSE"))
        .collect();
    let corrected = report["corrected_rmse"].as_f64().expect("corrected_rmse");
    let worst = values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let best = values.iter().cloned().fold(f64::INFINITY, f64::min);
    println!("fold RMSEs {values:?}, in-sample corrected {corrected:.4} dB");

    // **D22's inverted pin** (2026-08-03). Every fold must now score near the in-sample RMSE,
    // because a strided fold's training set spans every value of every axis and so scores an
    // interpolation rather than an extrapolation past the fitted knots.
    //
    // The bar is on the worst fold against a fixed dB threshold rather than on the worst/best
    // *ratio*: a ratio couples two independently moving numbers, so an unrelated change to
    // one fold could fail it for no reason. 0.5 dB is an order below the smallest number the
    // old blocked assignment produced on its edge folds (0.56 dB — and its worst was 10.86),
    // so a regression to contiguous slices cannot slip under it, while sitting a comfortable
    // 8× above the 0.0602 dB measured here.
    const WORST_FOLD_MAX_DB: f64 = 0.5;
    assert!(
        worst < WORST_FOLD_MAX_DB,
        "a cross-validation fold is scoring an extrapolation again (folds {values:?}, worst \
         {worst:.4} dB, best {best:.4} dB, in-sample {corrected:.4} dB). Strided folds \
         measured 0.0286 / 0.0312 / 0.0305 / 0.0602 / 0.0458 dB on 2026-08-03; the blocked \
         assignment D22 replaced gave 10.07 / 0.56 / 0.12 / 0.64 / 10.86. Check \
         validator::perform_cross_validation's fold assignment first."
    );

    // The whole point of striding is that no fold is *special*. Under the blocked assignment
    // the spread was 89× (0.12 to 10.86); requiring the worst to stay within an order of
    // magnitude of the best is what distinguishes "every fold interpolates" from "they all
    // happen to be small today".
    assert!(
        worst < 10.0 * best,
        "fold RMSEs still show two populations (worst {worst:.4} dB vs best {best:.4} dB, \
         folds {values:?}) — strided folds should all be scoring the same kind of question"
    );

    // Cross-validation must have completed: this grid is sized so every training split clears
    // the coefficient count (2592 against 960). Since D22 a fold failure is recorded rather
    // than fatal, so without this the test would pass on a run where no fold was scored at all.
    let failed = report["cross_validation"]["failed_folds"]
        .as_array()
        .map(|f| f.len())
        .unwrap_or(0);
    assert_eq!(
        failed, 0,
        "every fold must refit: this grid is sized for it (3240 points, 2592 per training \
         split, 960 coefficients). Report:\n{report:#}"
    );
}

/// **Roadmap C13, end to end.** A full-mode artifact's on-axis feed must serve *at the focus*.
///
/// The artifact field is the feed's design offset **from the focal point**, and the service
/// adds it to an already-vertex-origin steering position. `calibrate` wrote it vertex-relative
/// until 2026-08-02, which put the feed at `z ≈ 2f` — 27.3 dB of boresight gain on this
/// antenna. No test could see that, because none served a full-mode artifact.
#[test]
fn served_feed_sits_at_the_focus() {
    let response = serve(0.0, 0.0, ANCHOR_FREQUENCY_MHZ);
    let offset = &response.geometry.physical_feed_offset_m;

    assert!(
        offset.x.abs() < 1e-6 && offset.y.abs() < 1e-6 && offset.z.abs() < 1e-6,
        "a full-mode artifact's on-axis feed must sit at the focal point when the feed is \
         aimed at the boresight target, got ({}, {}, {}) m — `feed_position_m` is being \
         written vertex-relative again (roadmap C13)",
        offset.x,
        offset.y,
        offset.z
    );
}

/// The geometry helper aims where it says it aims.
///
/// It replicates the service's own antenna-frame construction, so this is the guard on that
/// replication: if the azimuth-zero convention ever moves, this fails with a clear message
/// instead of silently rotating every anchor comparison in the file.
#[test]
fn request_geometry_lands_on_the_requested_angles() {
    for (cone_deg, clock_deg) in [
        (0.0, 0.0),
        (4.0, 0.0),
        (5.3, 90.0),
        (10.8, 180.0),
        (7.0, 270.0),
    ] {
        let response = serve(cone_deg, clock_deg, ANCHOR_FREQUENCY_MHZ);
        let geometry = &response.geometry;

        assert!(
            (geometry.emitter_elevation_deg - cone_deg).abs() < 1e-6,
            "requested cone {cone_deg}°, served {}°",
            geometry.emitter_elevation_deg
        );
        // Azimuth is degenerate at the pole, so it is only meaningful off boresight.
        if cone_deg > 0.0 {
            let delta = (geometry.emitter_azimuth_deg - clock_deg).abs();
            assert!(
                delta.min(360.0 - delta) < 1e-6,
                "requested clock {clock_deg}°, served {}°",
                geometry.emitter_azimuth_deg
            );
        }
    }
}

// ============================================================================
// The pipeline reproduces the fill
// ============================================================================

/// The generator and the calibrator must build the *same* physics model from the same antenna
/// class, or the residual the correction surface fits is not the residual the fill injected.
///
/// The generator writes `model + residual` and calibrate differences its own model back out,
/// so calibrate's model-only RMSE has to equal the residual RMS the generator reports. This
/// is roadmap D17's question — "do the two sides of the pipeline evaluate the same model?" —
/// asked at the seam between calibrate and its input data.
#[test]
fn calibrate_and_the_generator_evaluate_the_same_model() {
    let run = pipeline();
    let injected = number(&run.summary, "injected_residual_rms_db");
    let model_only = run.report["model_only_rmse"]
        .as_f64()
        .expect("model_only_rmse in the validation report");

    println!(
        "injected residual RMS {injected:.4} dB, calibrate model-only RMSE {model_only:.4} dB"
    );
    assert!(
        (injected - model_only).abs() < MODEL_AGREEMENT_DB,
        "the generator injected a residual of RMS {injected:.6} dB but calibrate measured \
         {model_only:.6} dB against its own model: the two sides are no longer building the \
         same antenna from {ANTENNA_CLASS}\n{}",
        run.calibrate_output
    );
}

#[test]
fn the_correction_surface_fits_the_fill() {
    let run = pipeline();
    let corrected = run.report["corrected_rmse"]
        .as_f64()
        .expect("corrected_rmse in the validation report");
    let model_only = run.report["model_only_rmse"]
        .as_f64()
        .expect("model_only_rmse");

    println!("model-only RMSE {model_only:.4} dB, corrected {corrected:.4} dB");
    assert!(
        corrected < CORRECTED_RMSE_CEILING_DB,
        "corrected RMSE {corrected:.4} dB regressed past the measured ceiling \
         {CORRECTED_RMSE_CEILING_DB:.4} dB"
    );
    assert!(
        model_only > 5.0,
        "the fill's residual should be large — idealised physical optics under-predicts this \
         antenna's measured sidelobes by 7–17 dB — so a small model-only RMSE means the fill \
         stopped injecting the measured residual (got {model_only:.4} dB)"
    );
}

/// The served correction reproduces, at every anchor, the residual the fill injected there.
///
/// This is the file's tight assertion: no measurement uncertainty enters it, only the chain
/// fill → CSV → fit → artifact → loader → 4D interpolator. Note the argument order — the 3D
/// surface's clock/cone map onto the 4D surface's azimuth/elevation.
#[test]
fn the_served_correction_reproduces_the_injected_residual() {
    let run = pipeline();
    let calibration = run.load();
    let surface = calibration
        .correction_surface
        .as_ref()
        .expect("correction surface");

    let mut worst = 0.0_f64;
    for anchor in run.anchors() {
        let correction = evaluate_correction(
            surface,
            anchor.clock_deg,
            anchor.cone_deg,
            ANCHOR_FREQUENCY_MHZ,
            calibration.validity_ranges.temperature_const,
        )
        .expect("evaluate the 4D correction surface")
        .correction_db;

        let error = (correction - anchor.trend_db).abs();
        worst = worst.max(error);
        println!(
            "anchor clock {:5.1} cone {:5.1}: injected {:+.4} dB, served correction {:+.4} dB, \
             err {:.4} dB",
            anchor.clock_deg, anchor.cone_deg, anchor.trend_db, correction, error
        );
    }

    assert!(
        worst <= CORRECTION_FIDELITY_DB,
        "the served correction should reproduce the injected residual within \
         {CORRECTION_FIDELITY_DB} dB; worst error was {worst:.4} dB"
    );
}

// ============================================================================
// The served calibrated pattern against the published measurements
// ============================================================================

/// The headline real-data assertion at boresight: the served gain is the report's gain.
///
/// Unlike everything below, this one is not envelope-read and carries no lobe-scale
/// structure — the main-beam apex is a single well-defined number on both sides.
#[test]
fn served_boresight_gain_reproduces_the_published_gain() {
    let response = serve(0.0, 0.0, ANCHOR_FREQUENCY_MHZ);
    let delta = response.gain_db - PUBLISHED_GAIN_DBI;

    println!(
        "served boresight {:.4} dBi vs published {PUBLISHED_GAIN_DBI} dBi ({delta:+.4} dB)",
        response.gain_db
    );
    assert!(
        correction_applied(&response),
        "the correction must be reached at boresight; got warnings {:?}",
        response.warnings
    );
    assert!(
        delta.abs() < BORESIGHT_BUDGET_DB,
        "served boresight gain {:.4} dBi is {delta:+.4} dB from the report's published \
         {PUBLISHED_GAIN_DBI} dBi, outside the {BORESIGHT_BUDGET_DB} dB budget (itself well \
         inside the anchor's own {ABSOLUTE_ANCHOR_UNCERTAINTY_DB} dB uncertainty)",
        response.gain_db
    );
}

/// Every digitized peak, served: within its itemised budget, and closer than the uncorrected
/// model was.
///
/// Read the budget in [`ANCHOR_STRUCTURE_ALLOWANCE_DB`] before changing anything here — its
/// largest term is a *reported limitation of the shipped correction-surface resolution*, and
/// widening it is not a way to make this pass.
#[test]
fn served_calibrated_pattern_reproduces_the_digitized_peaks() {
    let run = pipeline();
    let anchors = run.anchors();

    // Measure the whole table first, then assert: a per-anchor panic would hide the rest of
    // it, and the rest of it is what says whether a failure is one bad point or a broken
    // pipeline.
    let measured: Vec<(&Anchor, f64, f64, f64)> = anchors
        .iter()
        .map(|anchor| {
            let served =
                served_envelope_dbi(anchor.cone_deg, anchor.clock_deg, ANCHOR_FREQUENCY_MHZ);
            let corrected_error = served - anchor.measured_dbi;
            let uncorrected_error = anchor.model_envelope_dbi - anchor.measured_dbi;
            (anchor, served, corrected_error, uncorrected_error)
        })
        .collect();

    for (anchor, served, corrected_error, uncorrected_error) in &measured {
        println!(
            "peak clock {:5.1} cone {:5.1}: measured {:7.2} dBi, served {served:7.2} dBi \
             ({corrected_error:+6.2} dB), uncorrected {:7.2} dBi ({uncorrected_error:+6.2} dB)",
            anchor.clock_deg, anchor.cone_deg, anchor.measured_dbi, anchor.model_envelope_dbi
        );
    }

    let corrected_rms =
        (measured.iter().map(|m| m.2 * m.2).sum::<f64>() / measured.len() as f64).sqrt();
    let uncorrected_rms =
        (measured.iter().map(|m| m.3 * m.3).sum::<f64>() / measured.len() as f64).sqrt();
    let improved = measured
        .iter()
        .filter(|(_, _, corrected, uncorrected)| corrected.abs() < uncorrected.abs())
        .count();
    println!(
        "over {} digitized peaks: uncorrected RMS {uncorrected_rms:.2} dB, corrected \
         {corrected_rms:.2} dB ({:.1}x better); corrected is closer at {improved}/{}",
        measured.len(),
        uncorrected_rms / corrected_rms,
        measured.len()
    );

    for (anchor, _, corrected_error, _) in &measured {
        let budget =
            anchor.uncertainty_db + ABSOLUTE_ANCHOR_UNCERTAINTY_DB + ANCHOR_STRUCTURE_ALLOWANCE_DB;
        assert!(
            corrected_error.abs() <= budget,
            "served peak at clock {}° cone {}° is {corrected_error:+.2} dB from the digitized \
             {:.2} dBi, outside its {budget:.2} dB budget ({:.1} dB digitization + \
             {ABSOLUTE_ANCHOR_UNCERTAINTY_DB} dB absolute anchor + \
             {ANCHOR_STRUCTURE_ALLOWANCE_DB} dB unrepresentable lobe structure)",
            anchor.clock_deg,
            anchor.cone_deg,
            anchor.measured_dbi,
            anchor.uncertainty_db
        );
    }

    assert!(
        corrected_rms <= ANCHOR_RMS_BUDGET_DB,
        "RMS error over the digitized peaks is {corrected_rms:.2} dB, past the measured \
         {ANCHOR_RMS_BUDGET_DB} dB budget"
    );
    assert!(
        uncorrected_rms / corrected_rms >= MIN_RMS_IMPROVEMENT_FACTOR,
        "the correction must improve on the uncorrected model by at least \
         {MIN_RMS_IMPROVEMENT_FACTOR}x in RMS over the digitized peaks; got \
         {uncorrected_rms:.2} dB → {corrected_rms:.2} dB"
    );
    assert!(
        improved >= MIN_ANCHORS_IMPROVED,
        "the calibrated pattern beat the uncorrected model at only {improved} of {} digitized \
         peaks, below the measured {MIN_ANCHORS_IMPROVED} — see the constant for which two \
         peaks are expected not to improve and why",
        measured.len()
    );
}

/// Off-boresight, in coverage, on a fully calibrated antenna: the correction is applied and
/// the response says so.
///
/// The `sa_8002a` half of D13 makes the same point on the boresight path. Here it also covers
/// the clock axis, which on this artifact carries only measured information.
#[test]
fn the_correction_is_reached_across_the_calibrated_region() {
    // Interior probes only. The coverage edges themselves (cone 14°, clock 0/350°) are
    // deliberately not probed: the served polar angle is recovered from the emitter geometry
    // through `acos`, so a request aimed at exactly the edge lands a few ULP outside the
    // inclusive bound and is served — correctly — as out of coverage.
    for (cone_deg, clock_deg) in [
        (0.0, 0.0),
        (3.0, 45.0),
        (7.0, 135.0),
        (11.0, 225.0),
        (13.5, 315.0),
    ] {
        let response = serve(cone_deg, clock_deg, ANCHOR_FREQUENCY_MHZ);
        assert!(
            correction_applied(&response),
            "the correction was skipped at cone {cone_deg}° clock {clock_deg}°, inside the \
             artifact's own coverage; warnings {:?}",
            response.warnings
        );
        assert_eq!(
            response
                .calibration_status
                .as_ref()
                .map(|s| s.status.as_str()),
            Some("fully_calibrated"),
            "a full-mode artifact must serve as fully calibrated at cone {cone_deg}° clock \
             {clock_deg}°"
        );
        assert!(
            response.metadata.spillover_loss_db.is_none(),
            "an artifact carrying a correction surface is served with spillover off (the \
             correction absorbs it empirically)"
        );
    }
}

// ============================================================================
// D21 — the artifact states the limitation its own RMSE cannot show
// ============================================================================

/// Cone knots per lobe period this artifact achieves.
///
/// Measured **0.5770**: `λ/D` = 1.1540° at the grid's top frequency (12.2 GHz, 1.22 m dish)
/// against a delivered 2.0° cone knot spacing — the fitter's six cone knots land on
/// 2/4/6/8/10/12°, exactly its 2° minimum spacing, and the widest gap is 2.0°.
///
/// This is the number behind the 3.19 dB anchor RMS above. Both are pinned, and they are not
/// independent: [`ANCHOR_STRUCTURE_ALLOWANCE_DB`] exists because of *this*.
const CONE_KNOTS_PER_LOBE_PERIOD: f64 = 0.5770;

/// Clock knots per lobe period, measured **0.1193** — five times worse than the cone axis.
///
/// Two reasons, and neither is the 5° minimum spacing the D21 filing named. The delivered
/// clock spacing is **40°**, eight times that floor, because eight requested knots over a
/// 350° axis is what binds. And the requirement is tighter than the cone axis's: traversing φ
/// at the coverage edge (cone 14°) crosses `sin 14°` of the pattern's angular scale, so the
/// clock lobe period is `1.1540° / sin 14°` = 4.770°.
///
/// Recorded because it inverts the filing's own reading: the axis the filing described as
/// having the laxer floor is the worse-resolved of the two.
const CLOCK_KNOTS_PER_LOBE_PERIOD: f64 = 0.1193;

/// The artifact carries its own angular resolution, and it says this antenna is not resolved.
///
/// The assertion that matters is the last one: the recorded figure must be *derived from this
/// artifact*, not a constant. Two independent checks force that — the cone ratio must match
/// `λ/D` computed here from the dish diameter and the grid's top frequency, and the clock
/// ratio must differ from the cone ratio by the `sin θ` factor. A build that stamped a
/// plausible fixed value would pass an equality check against one measured number and fail
/// both of these.
#[test]
fn the_artifact_records_that_its_knots_cannot_resolve_this_antennas_lobe_structure() {
    let calibration = pipeline().load();
    let resolution = calibration
        .metadata
        .angular_resolution
        .as_ref()
        .expect("a full-mode artifact must record its angular resolution");

    assert!(
        !resolution.resolves_lobe_structure(),
        "this 1.22 m dish at 12.1 GHz cannot be resolved by 2° cone knots, and the artifact \
         must say so: {}",
        resolution.summary()
    );

    for (label, measured, pinned) in [
        (
            "cone",
            resolution.cone_knots_per_lobe_period(),
            CONE_KNOTS_PER_LOBE_PERIOD,
        ),
        (
            "clock",
            resolution.clock_knots_per_lobe_period(),
            CLOCK_KNOTS_PER_LOBE_PERIOD,
        ),
    ] {
        assert!(
            (measured - pinned).abs() < 0.001,
            "{label} knots per lobe period moved: {measured:.4} against a pinned {pinned:.4}. \
             If the knot configuration changed deliberately, re-measure this and the anchor \
             budgets with it — they describe the same limitation. Full assessment: {}",
            resolution.summary()
        );
    }

    // Derived here from the dish geometry, so the recorded value cannot be a constant that
    // happens to match. 1.22 m is the class fixture's diameter; 12.2 GHz is the grid's
    // highest frequency, which is the frequency the assessment must use (shortest wavelength,
    // finest structure) — not the 12.1 GHz anchor frequency.
    let expected_lobe_period_deg = (299_792_458.0 / 12_200e6 / 1.22_f64).to_degrees();
    assert!(
        (resolution.cone_lobe_period_deg - expected_lobe_period_deg).abs() < 1e-6,
        "the recorded cone lobe period {:.6}° must be λ/D at the grid's top frequency \
         ({expected_lobe_period_deg:.6}°)",
        resolution.cone_lobe_period_deg
    );

    let sin_coverage_edge = 14.0_f64.to_radians().sin();
    assert!(
        (resolution.clock_lobe_period_deg * sin_coverage_edge - resolution.cone_lobe_period_deg)
            .abs()
            < 1e-6,
        "the clock lobe period must be the cone period divided by sin(coverage edge); got \
         {:.6}° against a cone period of {:.6}°",
        resolution.clock_lobe_period_deg,
        resolution.cone_lobe_period_deg
    );
}

/// The run that produced the artifact said so out loud, and said it as a warning.
///
/// The artifact metadata is for consumers; this is for whoever ran `calibrate` and read the
/// 0.0272 dB in-sample RMSE two lines above it. That number cannot see this limitation — the
/// grid is sampled no finer than the knots — so the run has to volunteer it.
#[test]
fn the_calibrate_run_warns_that_the_surface_cannot_resolve_the_lobe_structure() {
    let output = &pipeline().calibrate_output;
    assert!(
        output.contains("cannot resolve this antenna's lobe structure"),
        "calibrate must warn on an under-resolved fit. Output:\n{output}"
    );
    assert!(
        output.contains("envelope trend"),
        "the warning must say what the artifact does carry, not only what it does not. \
         Output:\n{output}"
    );
}
